services:
  discord-bot:
    build: .
    container_name: malaz-bott
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount a volume for logs
      - ./logs:/app/logs
    # Optional: add health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3 